---
title: "**Auburn Police Tactical Wellness Program**"
author: '*report generated by: Derek Anderson (dba0013@auburn.edu)*'
date: '*date: 2026-04-20*'
output:
  pdf_document:
    toc: true
  md_document:
    variant: gfm
  word_document:
    toc: false
  html_document:
    toc: true
    toc_float: true
---




\begin{center}\includegraphics[width=200px]{logo} \end{center}
\newpage

# Auburn Police Department Fitness Assessment

  Thank you for participating in the Auburn Police Department Fitness Assessment. During your visit, several aspects of your physical fitness were evaluated, including aerobic (cardiorespiratory) fitness, muscular strength, muscular endurance, lower-body power, flexibility, body composition, and balance. These measures provide an overall picture of your current physical readiness and general health.
  Your results will be compared to established normative fitness standards, which may account for factors such as age and sex, to help interpret how your performance compares to typical values seen in similar populations. In addition, you will receive information showing how your results compare to the overall performance of other members of the Auburn Police Department who participated in the assessment.
  
# Participant Identification and Confidentiality Statement

  The information contained in this report is associated only with Participant ID: **PFS_001**. To protect personal privacy, individual names and other identifying information are not included in this document. All results are recorded and reported using only the assigned participant identification number.
  This report is intended solely for the individual participant associated with this identification number. The information presented reflects personal fitness and health assessment results and should be treated as confidential. Participants are encouraged to maintain control of this document and share it only at their own discretion.
  Any summaries produced from this program will present group-level results only. These summaries will not contain any information that could be used to identify individual participants.

\newpage

# Body Composition

\begin{longtable}[t]{llllll}
\caption{\label{tab:body-comp-table}**Body Composition Summary Table**}\\
\toprule
Measurement & Value & Measurement & Value & Measurement & Value\\
\midrule
\cellcolor{gray!10}{Height (in)} & \cellcolor{gray!10}{65.2} & \cellcolor{gray!10}{Body Fat (\% of Body Weight)} & \cellcolor{gray!10}{13.7} & \cellcolor{gray!10}{Bone Density (g/cm2)} & \cellcolor{gray!10}{1.188}\\
Weight (lbs) & 148 & Body Fat \% Category & Excellent & Bone Density (Age and Sex \%ile) & 61\\
\cellcolor{gray!10}{BMI} & \cellcolor{gray!10}{24.4} & \cellcolor{gray!10}{Fat Mass (lbs)} & \cellcolor{gray!10}{20.3} & \cellcolor{gray!10}{Bone Mineral Content (lbs)} & \cellcolor{gray!10}{6.3}\\
BMI Category & Normal & Lean Muscle Mass (lbs) & 127.7 & Resting Metabolic Rate (cal/day) & 1488\\
\cellcolor{gray!10}{} & \cellcolor{gray!10}{} & \cellcolor{gray!10}{Lean Muscle Mass (\% of Body Weight)} & \cellcolor{gray!10}{86.3} & \cellcolor{gray!10}{} & \cellcolor{gray!10}{}\\
\bottomrule
\end{longtable}

Your Body Mass Index is **24.4**, placing you in the **Normal** category. Your body mass index is determined using your height and weight and does not take into account individual differences in muscle and fat mass. We assessed your body composition using dual-energy X-ray absorptiometry (DEXA), which is considered the gold standard of assessment techniques. Your body fat percentage is **13.7%**, and accounting for your age and sex, this places you in the **Excellent** category. Your bone mineral density percentile places you at the **61%ile** of people your age (note: this number is not the percentage of your total body mass that is bone mineral content).

Your resting metabolic rate is **1488** calories per day. Note that this amount is only enough to support your baseline physiological needs and does not account for the energy required to perform physical activity. If you are trying to **lose weight**, you may need approximately **1637** to **1934** calories per day. If you are trying to **maintain your weight**, you may need approximately **2083** to **2381** calories per day. If you are trying to **gain weight or are extremely physically active**, you may need **2530** calories per day or more.

\newpage

# Physical Performance


Table: **Physical Performance Summary Table**

|Test                          |Result |Category      |Test               |Result |Category      |
|:-----------------------------|:------|:-------------|:------------------|:------|:-------------|
|Estimated VO2 Max (mL/kg/min) |51.46  |Excellent     |Vertical Jump (in) |28.3   |Superior      |
|Grip Strength - Left (lbs)    |120.5  |Above Average |Plank (mm:ss)      |3:14   |Above Average |
|Grip Strength - Right (lbs)   |128.1  |Above Average |Bench Press (reps) |22     |Above Average |

The results of your physical performance tests are listed above. Aerobic fitness is important for normal daily function, and reduced aerobic capacity is associated with premature death and disability. To evaluate your aerobic fitness, we used a graded exercise test (GXT), a standard protocol widely used in clinical and fitness settings. This protocol estimates your body's ability to deliver and utilize oxygen to working muscles, also known as your VO~2~Max. Your VO~2~Max of **51.46** mL/kg/min for your age and sex places you in the **Excellent** category.

We evaluated your muscular fitness using four exercises: the YMCA bench press test, handgrip strength test, plank test, and vertical jump test. The YMCA bench press test measures upper-body muscular strength and endurance, which reflects how well your chest, shoulders, and arms can repeatedly perform pushing movements. The handgrip strength test measures grip strength, which is associated with the strength of several major muscle groups in the upper body. Grip strength is also important for many everyday and occupational tasks such as lifting, carrying, and maintaining control during physical activities. The plank test measures the muscular endurance of the core muscles, including the abdominal and lower back muscles. These muscles help stabilize the body and support posture during movement. The vertical jump test measures lower-body power, which reflects your ability to generate force quickly using the muscles of the hips and legs. This type of power is important for movements such as sprinting, jumping, and quickly changing direction. Overall, these results, together with your estimated VO~2~Max, provide a snapshot of your current fitness level and help identify areas where additional training may be beneficial.

Your YMCA bench press test score of **22** repetitions places you in the **Above Average** category for your age and sex. Your dominant-side grip strength was rated **Above Average**, and your non-dominant side was rated **Above Average**. Your plank test score places the muscular endurance of your core muscles in the **Above Average** category. Your vertical jump score of **28.3** inches places you in the **Superior** category for your sex and age.

\newpage

# Flexibility and Mobility


Table: **Flexibility and Mobility Results**

|Assessment                |Score |Category / Finding     |
|:-------------------------|:-----|:----------------------|
|Sit and Reach (in)        |14.44 |Fair                   |
|Functional Reach (in)     |16.7  |Average                |
|FMS - Overhead Squat      |2     |Sufficient Performance |
|FMS - Modified Push-Up    |3     |Excellent Performance  |
|FMS Pain - Left Shoulder  |0     |No Pain                |
|FMS Pain - Right Shoulder |0     |No Pain                |
|FMS Pain - Prone Press    |0     |No Pain                |
|FMS Pain - Posterior Rock |0     |No Pain                |

We assessed your flexibility and mobility using the YMCA Sit-and-Reach test, the Functional Reach test, and several items from the Functional Movement Screening (FMS). Flexibility is important for maintaining good posture and balance, reducing your risk of falling when your balance is challenged, and preventing low-back pain.

Your sit-and-reach score of **14.44** inches places you in the **Fair** category for your age and sex. Your functional reach score of **16.7** inches is classified as **Average**.

The FMS modified push-up was used to assess trunk stability. Your score of **3** indicates **Excellent Performance**. The FMS overhead squat was used to assess full-body kinetic function. Your score of **2** indicates **Sufficient Performance**.

During the assessment, three pain-provocation screens were completed. The main focus of these screens is to identify heightened injury risk and key compensatory movement patterns associated with poor mobility and/or stability. Your screens indicated:

- **Shoulder Clearing Test:** No Pain in the Left Shoulder; No Pain in the Right Shoulder
- **Spinal Extension - Prone Press Up Test:** No Pain
- **Spinal Flexion - Posterior Rock Test:** No Pain

\newpage

# Comparison To the Force

The above tables represent how well you compare to individuals of similar age and or sex. The comparisons in this section will show how you compare to your peers and to the Auburn Police Force across a variety of key metrics.

The charts below represent department-wide distributions. The dashed blue line marks your value; the label shows your percentile rank among all participating officers.




![](wellness_report_ind_files/figure-latex/comparison-plots-1.pdf)<!-- --> ![](wellness_report_ind_files/figure-latex/comparison-plots-2.pdf)<!-- --> ![](wellness_report_ind_files/figure-latex/comparison-plots-3.pdf)<!-- --> ![](wellness_report_ind_files/figure-latex/comparison-plots-4.pdf)<!-- --> ![](wellness_report_ind_files/figure-latex/comparison-plots-5.pdf)<!-- --> ![](wellness_report_ind_files/figure-latex/comparison-plots-6.pdf)<!-- --> ![](wellness_report_ind_files/figure-latex/comparison-plots-7.pdf)<!-- --> ![](wellness_report_ind_files/figure-latex/comparison-plots-8.pdf)<!-- --> ![](wellness_report_ind_files/figure-latex/comparison-plots-9.pdf)<!-- --> 
