% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Auburn Police Tactical Wellness Program},
  pdfauthor={report generated by: Derek Anderson (dba0013@auburn.edu)},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{\textbf{Auburn Police Tactical Wellness Program}}
\author{\emph{report generated by: Derek Anderson
(\href{mailto:dba0013@auburn.edu}{\nolinkurl{dba0013@auburn.edu}})}}
\date{\emph{date: 2026-04-20}}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\begin{center}\includegraphics[width=200px]{logo} \end{center}
\newpage

\section{Auburn Police Department Fitness
Assessment}\label{auburn-police-department-fitness-assessment}

Thank you for participating in the Auburn Police Department Fitness
Assessment. During your visit, several aspects of your physical fitness
were evaluated, including aerobic (cardiorespiratory) fitness, muscular
strength, muscular endurance, lower-body power, flexibility, body
composition, and balance. These measures provide an overall picture of
your current physical readiness and general health. Your results will be
compared to established normative fitness standards, which may account
for factors such as age and sex, to help interpret how your performance
compares to typical values seen in similar populations. In addition, you
will receive information showing how your results compare to the overall
performance of other members of the Auburn Police Department who
participated in the assessment.

\section{Participant Identification and Confidentiality
Statement}\label{participant-identification-and-confidentiality-statement}

The information contained in this report is associated only with
Participant ID: \textbf{PFS\_001}. To protect personal privacy,
individual names and other identifying information are not included in
this document. All results are recorded and reported using only the
assigned participant identification number. This report is intended
solely for the individual participant associated with this
identification number. The information presented reflects personal
fitness and health assessment results and should be treated as
confidential. Participants are encouraged to maintain control of this
document and share it only at their own discretion. Any summaries
produced from this program will present group-level results only. These
summaries will not contain any information that could be used to
identify individual participants.

\newpage

\section{Body Composition}\label{body-composition}

\begin{longtable}[t]{llllll}
\caption{\label{tab:body-comp-table}**Body Composition Summary Table**}\\
\toprule
Measurement & Value & Measurement & Value & Measurement & Value\\
\midrule
\cellcolor{gray!10}{Height (in)} & \cellcolor{gray!10}{65.2} & \cellcolor{gray!10}{Body Fat (\% of Body Weight)} & \cellcolor{gray!10}{13.7} & \cellcolor{gray!10}{Bone Density (g/cm2)} & \cellcolor{gray!10}{1.188}\\
Weight (lbs) & 148 & Body Fat \% Category & Excellent & Bone Density (Age and Sex \%ile) & 61\\
\cellcolor{gray!10}{BMI} & \cellcolor{gray!10}{24.4} & \cellcolor{gray!10}{Fat Mass (lbs)} & \cellcolor{gray!10}{20.3} & \cellcolor{gray!10}{Bone Mineral Content (lbs)} & \cellcolor{gray!10}{6.3}\\
BMI Category & Normal & Lean Muscle Mass (lbs) & 127.7 & Resting Metabolic Rate (cal/day) & 1488\\
\cellcolor{gray!10}{} & \cellcolor{gray!10}{} & \cellcolor{gray!10}{Lean Muscle Mass (\% of Body Weight)} & \cellcolor{gray!10}{86.3} & \cellcolor{gray!10}{} & \cellcolor{gray!10}{}\\
\bottomrule
\end{longtable}

Your Body Mass Index is \textbf{24.4}, placing you in the
\textbf{Normal} category. Your body mass index is determined using your
height and weight and does not take into account individual differences
in muscle and fat mass. We assessed your body composition using
dual-energy X-ray absorptiometry (DEXA), which is considered the gold
standard of assessment techniques. Your body fat percentage is
\textbf{13.7\%}, and accounting for your age and sex, this places you in
the \textbf{Excellent} category. Your bone mineral density percentile
places you at the \textbf{61\%ile} of people your age (note: this number
is not the percentage of your total body mass that is bone mineral
content).

Your resting metabolic rate is \textbf{1488} calories per day. Note that
this amount is only enough to support your baseline physiological needs
and does not account for the energy required to perform physical
activity. If you are trying to \textbf{lose weight}, you may need
approximately \textbf{1637} to \textbf{1934} calories per day. If you
are trying to \textbf{maintain your weight}, you may need approximately
\textbf{2083} to \textbf{2381} calories per day. If you are trying to
\textbf{gain weight or are extremely physically active}, you may need
\textbf{2530} calories per day or more.

\newpage

\section{Physical Performance}\label{physical-performance}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.3297}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0769}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1538}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2088}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0769}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1538}}@{}}
\caption{\textbf{Physical Performance Summary Table}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Test
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Result
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Category
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Test
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Result
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Category
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Test
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Result
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Category
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Test
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Result
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Category
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Estimated VO2 Max (mL/kg/min) & 51.46 & Excellent & Vertical Jump (in) &
28.3 & Superior \\
Grip Strength - Left (lbs) & 120.5 & Above Average & Plank (mm:ss) &
3:14 & Above Average \\
Grip Strength - Right (lbs) & 128.1 & Above Average & Bench Press (reps)
& 22 & Above Average \\
\end{longtable}

The results of your physical performance tests are listed above. Aerobic
fitness is important for normal daily function, and reduced aerobic
capacity is associated with premature death and disability. To evaluate
your aerobic fitness, we used a graded exercise test (GXT), a standard
protocol widely used in clinical and fitness settings. This protocol
estimates your body's ability to deliver and utilize oxygen to working
muscles, also known as your VO\textsubscript{2}Max. Your
VO\textsubscript{2}Max of \textbf{51.46} mL/kg/min for your age and sex
places you in the \textbf{Excellent} category.

We evaluated your muscular fitness using four exercises: the YMCA bench
press test, handgrip strength test, plank test, and vertical jump test.
The YMCA bench press test measures upper-body muscular strength and
endurance, which reflects how well your chest, shoulders, and arms can
repeatedly perform pushing movements. The handgrip strength test
measures grip strength, which is associated with the strength of several
major muscle groups in the upper body. Grip strength is also important
for many everyday and occupational tasks such as lifting, carrying, and
maintaining control during physical activities. The plank test measures
the muscular endurance of the core muscles, including the abdominal and
lower back muscles. These muscles help stabilize the body and support
posture during movement. The vertical jump test measures lower-body
power, which reflects your ability to generate force quickly using the
muscles of the hips and legs. This type of power is important for
movements such as sprinting, jumping, and quickly changing direction.
Overall, these results, together with your estimated
VO\textsubscript{2}Max, provide a snapshot of your current fitness level
and help identify areas where additional training may be beneficial.

Your YMCA bench press test score of \textbf{22} repetitions places you
in the \textbf{Above Average} category for your age and sex. Your
dominant-side grip strength was rated \textbf{Above Average}, and your
non-dominant side was rated \textbf{Above Average}. Your plank test
score places the muscular endurance of your core muscles in the
\textbf{Above Average} category. Your vertical jump score of
\textbf{28.3} inches places you in the \textbf{Superior} category for
your sex and age.

\newpage

\section{Flexibility and Mobility}\label{flexibility-and-mobility}

\begin{longtable}[]{@{}lll@{}}
\caption{\textbf{Flexibility and Mobility Results}}\tabularnewline
\toprule\noalign{}
Assessment & Score & Category / Finding \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Assessment & Score & Category / Finding \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Sit and Reach (in) & 14.44 & Fair \\
Functional Reach (in) & 16.7 & Average \\
FMS - Overhead Squat & 2 & Sufficient Performance \\
FMS - Modified Push-Up & 3 & Excellent Performance \\
FMS Pain - Left Shoulder & 0 & No Pain \\
FMS Pain - Right Shoulder & 0 & No Pain \\
FMS Pain - Prone Press & 0 & No Pain \\
FMS Pain - Posterior Rock & 0 & No Pain \\
\end{longtable}

We assessed your flexibility and mobility using the YMCA Sit-and-Reach
test, the Functional Reach test, and several items from the Functional
Movement Screening (FMS). Flexibility is important for maintaining good
posture and balance, reducing your risk of falling when your balance is
challenged, and preventing low-back pain.

Your sit-and-reach score of \textbf{14.44} inches places you in the
\textbf{Fair} category for your age and sex. Your functional reach score
of \textbf{16.7} inches is classified as \textbf{Average}.

The FMS modified push-up was used to assess trunk stability. Your score
of \textbf{3} indicates \textbf{Excellent Performance}. The FMS overhead
squat was used to assess full-body kinetic function. Your score of
\textbf{2} indicates \textbf{Sufficient Performance}.

During the assessment, three pain-provocation screens were completed.
The main focus of these screens is to identify heightened injury risk
and key compensatory movement patterns associated with poor mobility
and/or stability. Your screens indicated:

\begin{itemize}
\tightlist
\item
  \textbf{Shoulder Clearing Test:} No Pain in the Left Shoulder; No Pain
  in the Right Shoulder
\item
  \textbf{Spinal Extension - Prone Press Up Test:} No Pain
\item
  \textbf{Spinal Flexion - Posterior Rock Test:} No Pain
\end{itemize}

\newpage

\section{Comparison To the Force}\label{comparison-to-the-force}

The above tables represent how well you compare to individuals of
similar age and or sex. The comparisons in this section will show how
you compare to your peers and to the Auburn Police Force across a
variety of key metrics.

The charts below represent department-wide distributions. The dashed
blue line marks your value; the label shows your percentile rank among
all participating officers.

\pandocbounded{\includegraphics[keepaspectratio]{wellness_report_ind_files/figure-latex/comparison-plots-1.pdf}}
\pandocbounded{\includegraphics[keepaspectratio]{wellness_report_ind_files/figure-latex/comparison-plots-2.pdf}}
\pandocbounded{\includegraphics[keepaspectratio]{wellness_report_ind_files/figure-latex/comparison-plots-3.pdf}}
\pandocbounded{\includegraphics[keepaspectratio]{wellness_report_ind_files/figure-latex/comparison-plots-4.pdf}}
\pandocbounded{\includegraphics[keepaspectratio]{wellness_report_ind_files/figure-latex/comparison-plots-5.pdf}}
\pandocbounded{\includegraphics[keepaspectratio]{wellness_report_ind_files/figure-latex/comparison-plots-6.pdf}}
\pandocbounded{\includegraphics[keepaspectratio]{wellness_report_ind_files/figure-latex/comparison-plots-7.pdf}}
\pandocbounded{\includegraphics[keepaspectratio]{wellness_report_ind_files/figure-latex/comparison-plots-8.pdf}}
\pandocbounded{\includegraphics[keepaspectratio]{wellness_report_ind_files/figure-latex/comparison-plots-9.pdf}}

\end{document}
